//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_comment
    {
        public tbl_comment()
        {
            this.tbl_product1 = new HashSet<tbl_product>();
        }
    
        public int comment_id { get; set; }
        public string comment_content { get; set; }
        public Nullable<int> comment_fk_pro { get; set; }
        public Nullable<int> comment_fk_user { get; set; }
    
        public virtual tbl_product tbl_product { get; set; }
        public virtual tbl_user tbl_user { get; set; }
        public virtual ICollection<tbl_product> tbl_product1 { get; set; }
    }
}
